#!/usr/bin/ruby


$hy = '[- .\\/]'

$y = '((19|20|\')?[0-9][0-9])'      #19 or 20 plus 2 digits

$jan = '(january|jan)'
$feb = '(february|feb)'
$mar = '(march|mar)'
$apr = '(april|apr)'
$may = '(may|may)'
$jun = '(june|jun)'
$jul = '(july|jul)'
$aug = '(august|aug)'
$sep = '(september|sep|sept)'
$oct = '(october|oct)'
$nov = '(november|nov)'
$dec = '(december|dec)'
$m_nums = '((0?[1-9])|(1[012]))'      #1-12, optionally zero-padded

$m = "(#{$jan}|#{$feb}|#{$mar}|#{$apr}|#{$may}|#{$jun}|#{$jul}|#{$aug}|#{$sep}|#{$oct}|#{$nov}|#{$dec}|#{$m_nums})"


raw1 = '([023]?1)(st)?'    
raw2 = '([02]?2)(nd)?'   
raw3 = '([02]?3)(rd)?'   
rawth = '(([02]?[4-9])|(1[1-9])|([123]0))(th)?'   
$d = "((#{raw1})|(#{raw2})|(#{raw3})|(#{rawth}))"

$datefmt = {
    yyyy_mm_dd: Regexp.new('\b' + $y + $hy + $m + $hy + $d + '\b', true),
    yyyy_dd_mm: Regexp.new('\b' + $y + $hy + $d + $hy + $m + '\b', true),
    dd_yyyy_mm: Regexp.new('\b' + $d + $hy + $y + $hy + $m + '\b', true),
    dd_mm_yyyy: Regexp.new('\b' + $d + $hy + $m + $hy + $y + '\b', true),
    mm_dd_yyyy: Regexp.new('\b' + $m + $hy + $d + $hy + $y + '\b', true),
    mm_yyyy_dd: Regexp.new('\b' + $m + $hy + $y + $hy + $d + '\b', true),
}

while line = gets() do
    $datefmt.each do |fmt, re|
        if ( re =~ line )
            puts "#{$~}: #{fmt}: #{line}"
        end
    end
end

