#!/usr/bin/ruby


$hy = ',?[- .\\/]'

$y = '((19|20|\')?[0-9][0-9])'      #19, 20, or ',  plus 2 digits

$jan = '(0?1|january|jan)'
$feb = '(0?2|february|feb)'
$mar = '(0?3|march|mar)'
$apr = '(0?4|april|apr)'
$may = '(0?5|may|may)'
$jun = '(0?6|june|jun)'
$jul = '(0?7|july|jul)'
$aug = '(0?8|august|aug)'
$sep = '(0?9|september|sep|sept)'
$oct = '(10|october|oct)'
$nov = '(11|november|nov)'
$dec = '(12|december|dec)'

$m = "(#{$jan}|#{$feb}|#{$mar}|#{$apr}|#{$may}|#{$jun}|#{$jul}|#{$aug}|#{$sep}|#{$oct}|#{$nov}|#{$dec})"

$d01 = '(0?1(st)?)'
$d02 = '(0?2(nd)?)'
$d03 = '(0?3(rd)?)'
$d04 = '(0?4(th)?)'
$d05 = '(0?5(th)?)'
$d06 = '(0?6(th)?)'
$d07 = '(0?7(th)?)'
$d08 = '(0?8(th)?)'
$d09 = '(0?9(th)?)'
$d10 = '(10(th)?)'
$d11 = '(11(th)?)'
$d12 = '(12(th)?)'
$d13 = '(13(th)?)'
$d14 = '(14(th)?)'
$d15 = '(15(th)?)'
$d16 = '(16(th)?)'
$d17 = '(17(th)?)'
$d18 = '(18(th)?)'
$d19 = '(19(th)?)'
$d20 = '(20(th)?)'
$d21 = '(21(st)?)'
$d22 = '(22(nd)?)'
$d23 = '(23(rd)?)'
$d24 = '(24(th)?)'
$d25 = '(25(th)?)'
$d26 = '(26(th)?)'
$d27 = '(27(th)?)'
$d28 = '(28(th)?)'
$d29 = '(29(th)?)'
$d30 = '(30(th)?)'
$d31 = '(31(st)?)'

$d = "(#{$d01}|#{$d02}|#{$d03}|#{$d04}|#{$d05}|#{$d06}|#{$d07}|#{$d08}|#{$d09}|#{$d10}|#{$d11}|#{$d12}|#{$d13}|#{$d14}|#{$d15}|#{$d16}|#{$d17}|#{$d18}|#{$d19}|#{$d20}|#{$d21}|#{$d22}|#{$d23}|#{$d24}|#{$d25}|#{$d26}|#{$d27}|#{$d28}|#{$d29}|#{$d30}|#{$d31})"

$datefmt = {
    yyyy_mm_dd: Regexp.new('\b' + $y + $hy + $m + $hy + $d + '\b', true),
    yyyy_dd_mm: Regexp.new('\b' + $y + $hy + $d + $hy + $m + '\b', true),
    dd_yyyy_mm: Regexp.new('\b' + $d + $hy + $y + $hy + $m + '\b', true),
    dd_mm_yyyy: Regexp.new('\b' + $d + $hy + $m + $hy + $y + '\b', true),
    mm_dd_yyyy: Regexp.new('\b' + $m + $hy + $d + $hy + $y + '\b', true),
    mm_yyyy_dd: Regexp.new('\b' + $m + $hy + $y + $hy + $d + '\b', true),
}

while line = gets() do
    $datefmt.each do |fmt, re|
        if ( re =~ line )
            puts "#{$~}: #{fmt}: #{line}"
        end
    end
end

